gpu_variant:
  #- cpu
  #- cuda  # [(win and x86_64) or (linux and x86_64)]
  - cuda  # [(win and x86_64) or linux]

cuda_compiler_version:
  #- None
  #- 12.9 # [(win and x86_64) or (linux and x86_64)]
  - 13.0 # [(win and x86_64) or linux]

pytorch:
  - 2.11

zip_keys:
  -
    - gpu_variant
    - cuda_compiler_version
