{% set name = "torchcodec" %}
{% set version = "0.14.0" %}
{% set build_num = 0 %}

package:
  name: torchcodec-split
  version: {{ version }}

source:
  - url: https://github.com/meta-pytorch/torchcodec/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 340d85964f4865b16831b14923e3608866afbe6d5253b46a7c496bcdfb70bffa
    patches:
      - patches/fix_third_party_interface_library_loading.patch
      - patches/use_correct_python_on_windows.patch # [win]

build:
  number: {{ build_num }}
  # Skip if linux-aarch and CUDA 12
  # skip if CPU and CUDA 12 (only want one CPU variant)
  # osx builds are missing torchvision 0.26 builds that work with pytorch2.11. Skip osx builds until this is fixed.
  skip: true # [ py<310 or (((gpu_variant == "cpu" and (linux or win)) or aarch64) and (cuda_compiler_version or "12").startswith("12")) or osx]
  string: cpu_torch{{ pytorch | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build_num }} # [gpu_variant == "cpu"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_torch{{ pytorch | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build_num }} # [gpu_variant == "cuda"]

outputs:
  - name: torchcodec
    version: {{ version }}
    build: 
      number: {{ build_num }}
      missing_dso_whitelist:
        - "$RPATH/libtorchcodec_core8.so"    # [linux]
        - "$RPATH/libtorchcodec_core8.dll"   # [win]
        - "$RPATH/libtorchcodec_core8.dylib" # [osx]
    script: build_torchcodec.sh # [unix]
    script: build_torchcodec.bat # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cuda') }} # [gpu_variant=="cuda"]
        - cmake
        - pkg-config
        - ninja
      host:
        - python
        - pip
        - setuptools
        - ffmpeg
        - libtorch {{ pytorch }}=*cpu*    # [gpu_variant=="cpu"]
        - libtorch {{ pytorch }}=*cuda*   # [gpu_variant=="cuda"]
        - pytorch {{ pytorch }}=*cpu*    # [gpu_variant=="cpu"]
        - pytorch {{ pytorch }}=*cuda*   # [gpu_variant=="cuda"]
        - pybind11
        # These are dev packages (headers etc.) for transitive dependencies of libtorch
        - cuda-version =={{ cuda_compiler_version }} # [gpu_variant == "cuda"]
        - cuda-driver-dev     # [gpu_variant == "cuda" and linux]
        - nccl                # [gpu_variant == "cuda" and linux]
        - cuda-cudart-dev     # [gpu_variant == "cuda"]
        - cuda-nvrtc-dev      # [gpu_variant == "cuda"]
        - cuda-nvtx-dev       # [gpu_variant == "cuda"]
        - cuda-nvml-dev       # [gpu_variant == "cuda"]
        - cuda-profiler-api   # [gpu_variant == "cuda"]
        - libcublas-dev       # [gpu_variant == "cuda"]
        - libcufft-dev        # [gpu_variant == "cuda"]
        - libcurand-dev       # [gpu_variant == "cuda"]
        - libcusolver-dev     # [gpu_variant == "cuda"]
        - libcusparse-dev     # [gpu_variant == "cuda"]
        - nvtx-c              # [gpu_variant == "cuda"]
        # These are actual torchcodec deps
        - libnpp-dev          # [gpu_variant == "cuda"]
            
      run:
        - python
        # We temporary relatex the pytorch dependency on to be compatible with torchvision,
        # see https://github.com/conda-forge/torchcodec-feedstock/pull/69#issuecomment-4751807811
        - pytorch {{ pytorch }}=*cpu*    # [gpu_variant=="cpu"]
        - pytorch {{ pytorch }}=*cuda*   # [gpu_variant=="cuda"]
        - __cuda                         # [gpu_variant=="cuda"]

    {% set tests = "test/test_version.py" %}
    {% set tests = tests + " test/test_frame_dataclasses.py" %}
    {% set tests = tests + " test/test_metadata.py" %}
    {% set tests = tests + " test/test_decoders.py" %}

    {% set tests_to_skip = "" %}
    {% set tests_to_skip = "--deselect test/third-party-interface/test_third_party_interface.py" %}                                         # [win or osx]
    {% set tests_to_skip =  tests_to_skip + " --deselect test/test_encoders.py::TestAudioEncoder::test_against_cli" %}                      # [win]
    {% set tests_to_skip =  tests_to_skip + " --deselect test/test_encoders.py::TestVideoEncoder::test_video_encoder_against_ffmpeg_cli" %} # [win]

    test:
      source_files:
        - test/
      requires:
        - pytest
        - numpy
        - pillow
        - torchvision
        - pip
      imports:
        - torchcodec
      commands:
        - pip check
        - pytest {{ tests }} -v -s  --durations=50 {{ tests_to_skip }}

about:
  home: https://github.com/meta-pytorch/torchcodec
  license: BSD-3-Clause
  license_file:
    - LICENSE
  license_family: BSD
  summary: TorchCodec is a Python library for decoding videos into PyTorch tensors, on CPU and CUDA GPU.
  description: |
    TorchCodec is a Python library for decoding video and audio data into PyTorch
    tensors, on CPU and CUDA GPU. It also supports video and audio encoding on
    CPU! It aims to be fast, easy to use, and well integrated into the PyTorch
    ecosystem. If you want to use PyTorch to train ML models on videos and audio,
    or run inference, TorchCodec is how you turn these into data.
  dev_url: https://github.com/meta-pytorch/torchcodec
  doc_url: https://meta-pytorch.org/torchcodec/stable/index.html


extra:
  recipe-maintainers:
    - traversaro
    - Dan-Flores
  feedstock-name: torchcodec
